service: dinner-tg-bot
useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  region: ap-southeast-1
  runtime: python3.7
  environment: 
    API_KEY: ${env:API_KEY}
    CHAT_ID: ${env:CHAT_ID}

functions:
  cronSendMessage:
    handler: handler.send_message
    events:
      - schedule: cron(0 8 ? * MON-FRI *)
  cronSendPoll:
    handler: handler.send_poll
    events:
      - schedule: cron(0 7 ? * MON-FRI *)
      - http:
          path: dinner-bot
          method: post
          cors: true
  
